### ISSUE TITLE
some h

### ISSUE THREAD

**Issue by DeltaNedas** [Xeloboyo/Factoriodustry#13]
bunch of stuff:
icon script for walls doesnt change icon(Cicon.full)
![1](https://user-images.githubusercontent.com/39013340/101800849-a3910e80-3b05-11eb-8c5c-82a7fdd4f904.jpg)
![2](https://user-images.githubusercontent.com/39013340/101800893-b1df2a80-3b05-11eb-9d8d-c059edf910b8.jpg)
mend proj, surge walls and liquid tank arent done yet
![3](https://user-images.githubusercontent.com/39013340/101800937-c0c5dd00-3b05-11eb-99d0-cda69ad6cd77.jpg)
armored conduit, bridge conduit, liquid router (block) arent done yet
![4](https://user-images.githubusercontent.com/39013340/101801023-d804ca80-3b05-11eb-9c39-b898b6184c78.jpg)
conduit corners are h

**Comment by Andrees2000** [comment]
How to download, or it's not ready?
