### ISSUE TITLE
Incompatible with Java 16

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [Xeloboyo/Factoriodustry#25]
| OS | Arch Linux |
|------|---------------|
| Java Version | OpenJDK build 16.0.1+9-24 (AUR) |
| Mindustry version | 126.2 (`mindustry-bin` package in AUR) |

If you need any more info please leave a comment

[Crash Report](https://github.com/Xeloboyo/Factoriodustry/files/6480959/crash-report-05_14_2021_20_56_55.txt)

![image](https://user-images.githubusercontent.com/52577747/118322457-0e040b80-b4f7-11eb-8379-608bdcaccbe2.png)

**Comment by EvilSquirrelGuy** [comment]
Seems to work fine with prior versions of java (tested with OpenJDK `15.0.2+7`), only version 16 seems to be causing this issue

**Comment by Xeloboyo** [comment]
Other mods have a similar issue at times, this is not something I can fix bc this mod is written in javascript not java. Only course of action is to revert to an earlier jdk until updates to mndustry, rhino, or the jdk have resolved the issue.
